### ISSUE TITLE
serial monitor: save linefeed option

### ISSUE THREAD

**Issue by jantje** [jantje/arduino-eclipse-plugin#142]
Now the serial monitor always reverts to the default (no linefeed) option.
Adding a "last used serial monitor option" would be nice.

**Comment by rlogiacco** [comment]
@jantje should I mark this with `waiting for confirmation`?

**Comment by jantje** [comment]
I guess this was one of those autocloses again :-(
So indeed this should be open and waiting for confirmation and after being confirmed to "fixed in nightly"

**Comment by jantje** [comment]
just tested this.
It is fixed.
Thanks roberto
