### ISSUE TITLE
Typo: ArduinoPivateLibPath should be ArduinoPrivateLibPath

### ISSUE THREAD

**Issue by brunnels** [jantje/arduino-eclipse-plugin#153]
Defined here https://github.com/jantje/arduino-eclipse-plugin/blob/ad9ece00d9d4820f952794b9c771f711d05ec2d4/it.baeyens.arduino.common/src/it/baeyens/arduino/common/ArduinoConst.java#L59

**Comment by jantje** [comment]
closing
