### ISSUE TITLE
arduino:arduino in boards.txt is not supported (for upload)

### ISSUE THREAD

**Issue by xaljox** [jantje/arduino-eclipse-plugin#158]
When opening the Arduino dialog of the project Properties (e.g. for selecting another USB port), then some path variables are reset to a wrong value. As a result the resource paths to the "arduino->core" and "arduino->variant" are wrong.
Lets show the original values of the path variables:
![schermafbeelding 2014-06-26 om 09 26 12](https://cloud.githubusercontent.com/assets/3994368/3395900/91884eaa-fd05-11e3-8075-8c31eb8aaeed.png)
Next select "Arduino" in the left pane of the Properties dialog:
![schermafbeelding 2014-06-26 om 09 26 40](https://cloud.githubusercontent.com/assets/3994368/3395920/f09e34b8-fd05-11e3-80dd-914bcfc3b8b3.png)
See that the "arduino->core" and "arduino->variant" items in the "Project Explorer" are directly marked as erroneous. 
When looking at the path variables, some of them are set wrong, the starting '/' is gone. It seems they are somehow reset to a wrong initial value.
![schermafbeelding 2014-06-26 om 09 28 55](https://cloud.githubusercontent.com/assets/3994368/3395940/60de13d8-fd06-11e3-8a76-16e3a8e0fbbe.png)
When those path variables are edited to at '/' at the front, the "arduino->variant" resource path is repaired, but the "arduino->core" is still fault.
![schermafbeelding 2014-06-26 om 09 30 04](https://cloud.githubusercontent.com/assets/3994368/3395947/9ac555a2-fd06-11e3-946b-841dc177d870.png)
This must be repaired by editing its Properties,  somehow this resource path is reseted to a very strange value with arduino:arduino in it. Magically the ':' expands to '::', but perhaps that is my lack of understanding eclipse.
Note that I used version mac64.2014-05-22_02-07-31.tar.gz of the eclipseArduino. I've no idea if Windows or Linux version suffer from the same issue.
I develop both on an iMac and MacBook air and transfer the projects between them. When switching to the other machine, I have there another USB port identifier, so I must alter it. 
Then I must always repair the resource paths, the first time it occurred, it took me a while to discover what was going on and how to repair it. Now I'm more comfortable with Eclipse and I'm able to fix it fast. I've added a path variable of my own, which is left untouched, so I just reset "arduino->core" to that variable. As for the other variables, after visiting the "Arduino" part, I visit immediately the path variable part, double click on the wrong ones and add a '/'.

**Comment by jantje** [comment]
reopening due to new labelling.
If anyone want to implement support for arduino:arduino please take ownership of this issue

**Comment by jantje** [comment]
it works now for core and variant.

**Comment by jantje** [comment]
I wonder if this is used in V3

**Comment by jantje** [comment]
In v3 this should not be used
