### ISSUE TITLE
Arduino IDE 1.5.7 no longer contains makefile in windows zip

### ISSUE THREAD

**Issue by ranm** [jantje/arduino-eclipse-plugin#183]
Hey ,
First I want to say I love this plugin and use it a lot. Lately I've installed a setup on my other PC, wanting to give V2.2 a try, and ran into some problems.
Using Eclipse Luna, Plugin version 2.2.0.1, when I create a new project the build doesn't work .
I get the following :
Cannot run program "make": Launching failed

Error: Program "make" not found in PATH
PATH=[C:/Arduino/hardware/tools/avr/bin/;;C:/Arduino/hardware/tools/avr/utils/bin;C:\Program Files (x86)\MATLAB\MATLAB Component Runtime\v77\runtime\win32\..\..\bin\win32;C:\Program Files (x86)\MATLAB\MATLAB Component Runtime\v77\runtime\win32;C:\Perl64\site\bin;C:\Perl64\bin;C:\Python27;c:\Program Files (x86)\AMD APP\bin\x86_64;c:\Program Files (x86)\AMD APP\bin\x86;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;c:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files\TortoiseSVN\bin;c:\Program Files (x86)\Microsoft SQL Server\90\Tools\binn\;C:\Program Files (x86)\QuickTime\QTSystem\;C:\Program Files (x86)\SlickEdit 2008\win\;C:\Program Files\7-Zip;c:\lzop]

Also , when I create a new project, the MCU project is not created as it should be . 
I'm used to working with V1 + kepler + arduino IDE 1.0.5 on my other PC and there everything works fine.
I tried re=installing the plugin and IDE with no luck. 
On this PC I'm using Luna , IDE 1.5.7 and V2.2 . Is there a  competebility issue here?
Thanks,
Ran.

**Comment by scoobydude** [comment]
Using latest Eclipse Luna SR2, Arduino IDE 1.6.1, Jantje Eclipse plugin 2.2.0.1, I still see 'Cannot run program "make": Launching failed'.  As suggested I copied Arduino\hardware\tools\avr\utils\bin\* from an earlier release (1.5.5) to the same location in 1.6.1 and it works now.

Since it appears the Arduino IDE has intentionally stopped including these tools(?), does anyone know the proper way to get/install them (on Windows)?

Overall very nice plugin Jantje.  Sorry no free beer today, but you've earned the respect of a long-time hacker :)
Thanks.

**Comment by jantje** [comment]
@scoobydude Arduino will probably never again come with a make utility again. If you find a "windows make utility" please let me know

**Comment by rlogiacco** [comment]
At this stage the only way to bring in the missing tools is the same process you have already applied.

I don't know if Jantje is willing to include the avr toolchain into the plugin or if, for any reason, he isn't, but at this stage and until we get a decision, this is the way to go.

Happy to know you already found it ;)

**Comment by jantje** [comment]
Advised is to install make utility on your os. See http://eclipse.baeyens.it/installAdvice.shtml read the "all os section" and your os section.

**Comment by jantje** [comment]
With the new configuration page which reports the existence of make in the path I think we can close this issue

**Comment by jantje** [comment]
With make being downloaded I remove the known limitation label
