### ISSUE TITLE
luna does not pick up the changes in header files correctly

### ISSUE THREAD

**Issue by jantje** [jantje/arduino-eclipse-plugin#186]
When a change is done in a header file the cpp files are not recompiled correctly.
Work around: Go to project properties->arduino->compile options and add -MT"$@"

for more info see http://forum.arduino.cc/index.php?topic=79595.msg1829961#msg1829961

**Comment by sjaco** [comment]
Hi,
I have the same problem. After some plugin-debugging I found the -MT option is wrong when being processed in addDependencyOptions(...) within class ArduinoGnuMakefileGenerator.

This results in a makefile rule being generated making the dep-file being dependent on the source and all the include file. This have to be changed to the object file with -MT"$@".

For me the following patch in the mentioned class solved the problem:

    /*
     * Add any dependency calculator options to the tool options
     */
    @SuppressWarnings("static-method")
    private String[] addDependencyOptions(IManagedDependencyCommands depCommands, String[] flags)
    {
        String[] depOptions = depCommands.getDependencyCommandOptions();
        if (depOptions != null && depOptions.length > 0)
        {
            int flagsLen = flags.length;
            String[] flagsCopy = new String[flags.length + depOptions.length];
            for (int i = 0; i < flags.length; i++)
            {
                flagsCopy[i] = flags[i];
            }
            for (int i = 0; i < depOptions.length; i++)
            {
                // FIXME: SJA Patch begins here.
                if (depOptions[i].startsWith("-MT"))
                {
                    depOptions[i] = "-MT\"$@\"";
                }
                // FIXME: SJA Patch ends here.

                flagsCopy[i + flagsLen] = depOptions[i];
            }
            return flagsCopy;
        }
        return flags;
    }


Great plugin. I really appreciate your work!

Beste regards,
    Stephan

**Comment by jantje** [comment]
@sjaco 
Thanks for the nice words and the fix proposal.
I think it is a workaround because the reason is the wrong input. But I'll implement it and we can see whether the problem goes away.

**Comment by jantje** [comment]
Since the fix this hasn't happened to me anymore. So I close this issue.
Please reopen if you experience this problem.
