### ISSUE TITLE
Please remove that annoying "What do you want the team to do next" popup

### ISSUE THREAD

**Issue by ip6li** [jantje/arduino-eclipse-plugin#204]
Please remove that annoying "What do you want the team to do next" popup which appears sometimes

**Comment by beingobserver** [comment]
Yes, i did donate and always told jantje how valuable his work.
And jantje closed my post because i shared my idea about his website as being too complicated.
I have spent a day trying to figure out which version of what software and plugin. I know that this is not a commercial product and jantje is spending too much time to improve this. But i think it was a bit rude to close my post because i shared my idea. https://github.com/jantje/arduino-eclipse-plugin/issues/218

**Comment by rlogiacco** [comment]
@beingobserver may I suggest you to try to suggest *where* and *how* it can be improved? 
That would be very appreciated as opposed to a sole negative feedback "it's too complicated" which doesn't help much other than telling us *your work is shit*.

Please remember the web site is available for modification here on Github, and it has been structured to allow *non-web-designers* to contribute. I'm sure Jantje will be happy to accept any contribution which can improve the plugin or the accompanying web site.

**Comment by beingobserver** [comment]
Did i say that your work is (sorry) "shit"? I didn't think so, i just told that it is complicated. 
Yes, i can always share my ideas about how to improve your site especially if someone wants to ask.

I think there are several problems with the "How to decide.." diagram which can answer many questions if you can re-think about it.

It asks questions like "Do i need pre Arduino IDE 1.5".
Instead, you can start with something like "If you have OS X 64 bit without any Arduino IDE or Eclipse" then "Download this" and "Download this" etc. This might be a bit more directive and helpful.

**Comment by rlogiacco** [comment]
That's very valuable input IMHO! BTW, I know you didn't say our work is crap, but that's how it came across: a little misunderstanding, I believe.

We might think about providing an alternative flow chart which starts with the OS version, if you believe that would help, but I don't think that's needed as the OS doesn't play a role (not considering defects).

I can understand the very first question doesn't make much sense to you, but there are situations where people need to use an old version.

So, if you follow the flow chart, in your situation it guides you toward the Arduino IDE 1.5.* and Plugin v2.* which, crossed with the know issues reported in the same page below, it means you need IDE 1.5.6 and Plugin Bundle 2.3 (latest stable).

Does it make sense?

Once again, improvements are very welcome and the website source code is available at https://github.com/jantje/arduino-eclipse-plugin/tree/master/Eclipse%20update%20site/WebContent: if you fork the project and improve it we will be very grateful.

**Comment by beingobserver** [comment]
Thank you rlogiacco.
I downloaded
- V2.3_mac64.2014-07-12_02-06-35.tar.gz
- Arduino 1.5.6 r2.
and unzipped to Application folder.

When i run Eclipse, it says "Version 1.6.0_65 of the jvm is not suitable for this product. Version 1.7 or greater is required". I don't know what to do next.

**Comment by TrippyLighting** [comment]
Ha Ha Ha. I got a good laugh about Jantje's reply. But ut was a little harsh ;-)
Great to hear that you donated! Excellent feedback on the instructions as well. I am not one of the developers, but wrote detailed Installation instructions http://trippylighting.com/teensy-arduino-ect/arduino-eclipse-plugin and I can see that for a newcomer this cane a little overwhelming. Ive worked with the plugin and now the IDE (that they can The Product) for 2 years and sometimes we loose sight of what it actually takes for a newcomer.

To address the nee for Java 7, there are two ways you can go about it.
1. Apple recently released an update to Java 8 here in the US. Perhaps check itf it's there in the Appstore and if not, you have to wait until its available in your part of the world.

2 the other thing you can do is just to install a newer version of the Java JRE from. http://www.oracle.com/technetwork/java/javase/downloads/jre7-downloads-1880261.html

I just did this recently and it worked like  charm.

**Comment by beingobserver** [comment]
Thank you TrippyLighting. I am downloading jre and jdk files now, i'll try.

Jantje thought that i didn't want to spend my time by trying to find the requirements from his web site. Actually i had spent a full day installing and uninstalling the things.

Thanks

**Comment by beingobserver** [comment]
TrippyLighting, thank you soo much! JRE made the trick.

**Comment by rlogiacco** [comment]
@beingobserver would you like to contribute a few lines to the web site to help the next one facing a similar issue? In the order of "When installing on MacOS please verify A,B,C" and so on

**Comment by beingobserver** [comment]
Of course. Its something like this.

First of all, check this page to know if your OS X is 32 bit or 64 bit:
- http://support.apple.com/en-us/HT3696

Then download these three.
1) Arduino 1.5.6 r2 from from http://arduino.cc/en/Main/OldSoftwareReleases
2) V2.3_mac64.2014-07-12_02-06-35.tar.gz from http://eclipse.baeyens.it/download.php
3) Java JRE 7 from. http://www.oracle.com/technetwork/java/javase/downloads/jre7-downloads-1880261.html

Put Arduino and Eclipse into your Applications folder and run Java JRE 7 .dmg file.

Thats it as far as i could remember.

Regards
