### ISSUE TITLE
Allow deep linking in the new website

### ISSUE THREAD

**Issue by rlogiacco** [jantje/arduino-eclipse-plugin#206]
The new website does not curently support deep linking, which means it is impossible, as an example, to send out a link to the troubleshooting section in the FAQs page. In fact the URL `http://eclipse.baeyens.it/rlogiacco/faq.shtml#/troubleshooting` opens up the general section (the default one) rather than the correct one.

**Comment by rlogiacco** [comment]
The two are not related.
There are many tools to generate .html from .md and if you prefer the generation approach we can definitely go that way, but I don't see great advantage other than supporting old browsers (pre IE 9-10) which might have difficulty in running the JavaScript used to parse the .md files.

I've created a pull request containing an implementation for the deep-linking, let's have a try on that and see if it's satisfactory or not.

**Comment by jantje** [comment]
Deep linking on the faq works now. 
I'm not sure on what you did with the how to page in regards to server side include but al seems to work fine for me.
