### ISSUE TITLE
Arduino Nanos with CH340G chipset for USB/Serial are not listed on Mac OS-X Yosemite

### ISSUE THREAD

**Issue by kigster** [jantje/arduino-eclipse-plugin#208]
I briefly looked at how the plugin gets list of available Serial ports, and I *think* it's going through RXTX library, which then goes through native ObjectiveC API, in the file SerialImp.c. The API seems to be using a kernel function:

```c
  kernResult = IOServiceGetMatchingServices(masterPort, classesToMatch, serialIterator);
```

For whatever reason this does not include the ports created by Nano with the above mentioned chipset.  This chipset does not currently have a Yosemite specific / signed driver, so this may be why the OS-X Api is not properly registering it as a serial port.  But it is available under /dev:

```bash
crw-rw-rw-   1 root  wheel      17,   4 Jan  1 16:40 tty.wchusbserial144140
crw-rw-rw-   1 root  wheel      17,   5 Jan  1 16:40 cu.wchusbserial144140
```
Is there a higher level call inside the plugin itself that can be modified to include these ports in the list of Serial ports?

See this link regarding how to install the drivers for these chipsets on Yosemite:
http://kiguino.moos.io/2014/12/31/how-to-use-arduino-nano-mini-pro-with-CH340G-on-mac-osx-yosemite.html

**Comment by jantje** [comment]
Some comments
1) The Arduino eclipse plugin lets you enter anything for serial port in the project properties or the create sketch wizard. There is no test on existence nor on format. During testing I mostly type "fff" or "ggg" as serial port. 
Apart from resetting the board via the serial port if needed the plugin simply doesn't use the port. If the resetting fails the plugin still tries to upload.
2) The serial monitor is a different story. There you can only select the found ports.
3) The latest version of the plugin no longer uses rxtx. This port has been done by  amorellgarcia and I haven't had a need to go and look into the code in detail. Thanks for the good work  amorellgarcia.
4) The rxtx library has "internal logic to filter ports". On linux there is a work around http://eclipse.baeyens.it/Arduino%20eclipse%20plugin%20FAQ.html#LinuxNoSerialPorts but I'm not sure this works on OS-X

My advice: upgrade to the latest nightly build and see whether you still have the issue.

**Comment by kigster** [comment]
Actually I am using nightly build of 2.4 :) If this serial port filtering logic exists in java, I would be happy to add support for this chipset myself and send a PR.

**Comment by kigster** [comment]
Any update on this?  Or pointers where in the source that logic lives, so that I can try to patch it?

**Comment by jantje** [comment]
Have you tried the latest version?

**Comment by kigster** [comment]
Not the latest, but at the time I logged this ticket I was on the HEAD.

On Mon, Mar 2, 2015 at 12:42 PM, jantje <notifications@github.com> wrote:

> Have you tried the latest version?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jantje/arduino-eclipse-plugin/issues/208#issuecomment-76815485>
> .
>



-- 


*Konstantin Gredeskoul*CTO :: Wanelo Inc
cell: (415) 265 1054

**Comment by jantje** [comment]
Och; I was not aware so I thought you'd check out the latest version.
The code you are looking for is 
in project it.baeyens.arduino.common 
in package it.baeyens.arduino.arduino 
in class Serial
the method list

Good luck

**Comment by jantje** [comment]
is there an update?

**Comment by jantje** [comment]
as I do not have the hardware (boards and osx) I'll mark this as a known limitation.
If you ever get to fix this please post

**Comment by jantje** [comment]
If anyone can confirm the fix is working fine that would be great :-)

**Comment by kigster** [comment]
I can, will try today.

**Comment by jantje** [comment]
Txs
If you want to use the "update" functionality, pleas wait untill tomorrow. This change will only be caught up by the nightly build.

**Comment by jantje** [comment]
@kigster did you find the time needed to test?

**Comment by kigster** [comment]
Hey – I tested this using the nightly build. 

On the positive note – they do show up in the list: both in the project's configuration, as well as the Serial console as shown below.

On the downside – it takes exactly 15 seconds to bring up each dialog. Whatever logic is scanning for ports is taking this long, which is definitely not ideal.

Hope this helps!

![properties_for_wallock](https://cloud.githubusercontent.com/assets/259982/11921421/810bd978-a73d-11e5-8767-a3d752ae6bf5.png)

![arduino_-_wallock_app_app_cpp_-_eclipse_-__users_kig_projects_eclipse](https://cloud.githubusercontent.com/assets/259982/11921422/836a4894-a73d-11e5-9528-ec3d7955555c.png)

**Comment by alexandrezia** [comment]
I'm using the nightly build as well,
And it's taking less then a second to show up all my serial ports.
Perhaps the regular expression:
```
portNames = SerialPortList.getPortNames("/dev/", Pattern.compile("tty.*"));
```
Should be narrowed a bit to exclude the device that's causing the delay.

**Comment by jantje** [comment]
I see no delay here as well.
@alexandrezia 
Any clue on a better regular expression?

**Comment by kigster** [comment]
Do you have the WSCH driver loaded, when it takes less than a second?

**Comment by kigster** [comment]
Pattern can be optimized as follows:
```java
...compile("^cu\..+");
```

**Comment by alexandrezia** [comment]
Yes, always loaded

**Comment by jantje** [comment]
Please advice on the actions I should take.

**Comment by alexandrezia** [comment]
I did some tests and found out that bluetooth serial connections could slow down serial port detection because these connections exists but are not actually active, takes some time.
So this is the most optimal regular expression I could found:
```
Pattern.compile("^cu\\..*(serial|usb).*"));
```
As it excludes bluetooth connections, it turned out to be real fast.

**Comment by alexandrezia** [comment]
Pull request:  https://github.com/jantje/arduino-eclipse-plugin/pull/335

**Comment by jantje** [comment]
merged :-)
txs.

**Comment by kigster** [comment]
Awesome, thanks! – the delay is now gone.

**Comment by jantje** [comment]
good than we can close this.
Thanks to all of you.
Jantje

**Comment by TrippyLighting** [comment]
@kigster would you be willing to share that dark theme in that can be seen in the screenshot other up in this thread... and also possibly how to install it ?
Sorry for hijacking this thread!

**Comment by wimjongman** [comment]
preferences: General/Appearance - Theme: Dark

**Comment by TrippyLighting** [comment]
Doh ;-) Thanks!
