### ISSUE TITLE
the downoad of stable win link does not work anymore

### ISSUE THREAD

**Issue by marcelrv** [jantje/arduino-eclipse-plugin#215]
http://www.baeyens.it/eclipse/stable-win.html

the stable win link does not work anymore

 ```
Not Found

The requested URL /download/product/V2.3_win32.2014-07-12_02-06-35.tar.gz was not found on this server.```

**Comment by jantje** [comment]
Indeed
But please use http://eclipse.baeyens.it/stable-win.html then it works fine.
Can you tell me where you found the http://www.baeyens.it/eclipse/ reference?
Best regards
Jantje

**Comment by jantje** [comment]
Should be fixed now.

**Comment by TrippyLighting** [comment]
I think I'll need to update the links and references in the instructions on my blog.

**Comment by marcelrv** [comment]
Hi
Arrived via google:
https://www.google.com/search?q=arduino+eclipse+&ie=utf-8&oe=utf-8
The 3rd link (for me) pointed to www.baeyens.it/eclipse/

Using the Install->Windows from the top menu bar.

**Comment by marcelrv** [comment]
Indeed fixed now

**Comment by jantje** [comment]
txs for the link. Unfortunately I don't know how to change google output ;-)

**Comment by rlogiacco** [comment]
It should self fix in a few days when google crawler will try to re-index the site. References from other sites though will have to be updated manually.
