### ISSUE TITLE
Mac OS. Eclipse doesn't recognise arduino mega

### ISSUE THREAD

**Issue by leikoilja** [jantje/arduino-eclipse-plugin#216]
Hello. I really love that plugin and would like so it work
I am using your arduino plugin on my mac book pro OS X 10.10.1; 
Eclipse Luna IDE for C/C++ Developers(4.4.1) for Mac OS X 64 Bit; 
Arduino ide 1.5.7; 
Late night plugin 2.4.0
i am using arduino mega 2560

But when i am trying to upload schetch on the arduino it shows me some error :/ (please see attached picture) 
![screen shot 2015-01-22 at 15 53 09](https://cloud.githubusercontent.com/assets/10655107/5857835/eab6442a-a24e-11e4-85e0-8929780ee986.png)

p.s. arduino works with arudino ide

**Comment by jantje** [comment]
Have you verified before the upload?
The plugin does not do a verify before upload.

**Comment by leikoilja** [comment]
How can I verify?

**Comment by TrippyLighting** [comment]
Try the "Verify" button. This is the green button to the left of the "upload" button ;-)

**Comment by leikoilja** [comment]
Ou. Sorry,  I just misunderstood the question then.  Yes,  I have tried pressinf verify,  nothing changes.

**Comment by jantje** [comment]
and the compilation was successfull?

**Comment by leikoilja** [comment]
oups, no it wasn't. It shows me mistake that file type is not found. But that's strange, cause i have set file type as it was written in the guide.
![screen shot 2015-01-23 at 15 41 59](https://cloud.githubusercontent.com/assets/10655107/5876329/a769cfb6-a316-11e4-974f-0a607008a570.png)
![screen shot 2015-01-23 at 15 42 15](https://cloud.githubusercontent.com/assets/10655107/5876330/a76d1414-a316-11e4-8dc0-a73e31850c7c.png)

**Comment by jantje** [comment]
The plugin is not correctly configured. It has to be *.ino and *.pde
See http://eclipse.baeyens.it/how_to.shtml#/e on how to configure correctly.
And visit http://eclipse.baeyens.it/donate.shtml to show your appreciation for the support.

**Comment by leikoilja** [comment]
I will show my appreciation as soon as i could make it work :/
okey, that was stupid error, i have solved it, but now it still shows some strange things
![screen shot 2015-01-23 at 16 14 19](https://cloud.githubusercontent.com/assets/10655107/5876900/66dc0fcc-a31b-11e4-8c90-efd2c41b4390.png)
and in the configuration plugin does not accept my Arduino.app
![10937865_832769846789170_387499989_n](https://cloud.githubusercontent.com/assets/10655107/5876951/df4f2dae-a31b-11e4-8bf3-de70fcda5962.jpg)

**Comment by jantje** [comment]
I guess you have installed older versions of the arduino IDE in /Applications/Arduino.app
I say so because the plugin uses .../content/resources/java/... and this is pre Arduino IDE 1.5.7.
In Arduino IDE 1.5.7 (and later) it should be .../Contents/Resources/Java/... as you  can read here https://github.com/jantje/arduino-eclipse-plugin/pull/180
I advice to completely remove the arduino app and reinstall it.

**Comment by leikoilja** [comment]
Installed 1.5.8, still the same error. 
Tried writing "/Applications/Arduino.app/Contents/Java" instead of /Applications/Arduino.app, but still it shows me the error "Value must be an existing file"

**Comment by jantje** [comment]
V2.2 of the plugin won't work.
Have you reselected the board in the board properties? That is vital when changing the underlying arduino IDE

**Comment by leikoilja** [comment]
Double checked, the board selected correctly. 
![screen shot 2015-01-24 at 14 40 48](https://cloud.githubusercontent.com/assets/10655107/5887551/39883ab6-a3d7-11e4-81cf-d5e39f7cbf3b.png)
I am getting that error now while compiling :/
![Uploading Screen Shot 2015-01-24 at 14.41.07.png . . .]()
and i still have that written in eclipce preferences 
![10945356_833168390082649_1445959501_n](https://cloud.githubusercontent.com/assets/10655107/5887557/841d86ee-a3d7-11e4-91fb-02092edb2f57.jpg)

**Comment by jantje** [comment]
as you can see the path is now correct set to  .../Contents/java/ instead of  .../Contents/Resources/Java/
so you made some progress.
Now all this is fine try to make a new sketch using the create sketch wizard.
I'm pretty sure this should work.

**Comment by leikoilja** [comment]
Have created a new sketch, even changed the microcontoller to arduino uno. Still got the same error, while compilation. 
Googled that error, found kind a solution to that:
![screen shot 2015-01-24 at 21 11 26](https://cloud.githubusercontent.com/assets/10655107/5888805/ceb9b002-a40d-11e4-9248-7d12169a68ea.png)
Have done how they advise... Got new errors :D :/
![screen shot 2015-01-24 at 21 11 07](https://cloud.githubusercontent.com/assets/10655107/5888807/dcc447fc-a40d-11e4-9d7a-7bcc4fc954b3.png)

**Comment by jantje** [comment]
the problem you have now is that you need to include Arduino.h in your ino files if you have no other libraries in use.

**Comment by leikoilja** [comment]
Can not believe THAT... successfully compiled :O :+1: 
![screen shot 2015-01-24 at 21 32 37](https://cloud.githubusercontent.com/assets/10655107/5888912/989c4a7c-a410-11e4-9966-8cf24af6db75.png)
p.s. i think if you could add exact version of eclipse & arduino ide, which are working, to your guide, it might help a lot of people :) 
Last question, if it possible to make commands such as "digitalWrite" to be highlighted? :) 


Oh.. tried to upload on my arduino uno got
![screen shot 2015-01-24 at 21 37 51](https://cloud.githubusercontent.com/assets/10655107/5888942/5c7d973e-a411-11e4-89ac-0f923955c60f.png)

**Comment by TrippyLighting** [comment]
Not sure this is still the case but in the past spaces in directory names were best avoided as Eclipse and/or the plugin encountered problems with spaces.
There is a space in ...../Eclipse workspace/.....
See if you can remove that and try again.

**Comment by leikoilja** [comment]
Yes yes yes yes yes yes, FINALLY!!!!
Thank you very much!!! Now it even compiled in other way: 
![screen shot 2015-01-25 at 00 09 10](https://cloud.githubusercontent.com/assets/10655107/5889431/721202f0-a426-11e4-8d4b-29960cdbf05c.png)

Before closing topic, i will ask once more, is it possible to make arduino functon highlighted? :) 
![screen shot 2015-01-25 at 00 08 05](https://cloud.githubusercontent.com/assets/10655107/5889433/8ff9b862-a426-11e4-9bde-c6287cf650c1.png)

**Comment by jantje** [comment]
>is it possible to make arduino functon highlighted?
yes an no.
It is possible to highlight a function but that would be all functions.
It is not possible to highlight the arduino functions and not the other functions.

**Comment by leikoilja** [comment]
how to make them highlighted? :)

**Comment by jantje** [comment]
preferences->C/C++->code style->Formatter

**Comment by jantje** [comment]
@leikoilja: Is everything working fine now?

**Comment by leikoilja** [comment]
@jantje, yes, thank you very much for help!
The only thing I haven't really found where i can make functions such as "digitalWrite" and etc. be coloured(highlighted). Even download some additional plugin called "Eclipse colorer" for C/C++ language, but turns out that is something else... it didn't help me :D

**Comment by rlogiacco** [comment]
The Eclipse editor syntax coloring is the way to go. You don't need any additional tools or plugins as Eclipse has a built-in engine.

The code formatter is for, well, formatting code and setting spacing, indentation and similar. You are looking for the syntax coloring preferences.

**Comment by jantje** [comment]
indeed syntax coloring not code formatter. My Bad.

And visit http://eclipse.baeyens.it/donate.shtml to show your appreciation for the support.
