### ISSUE TITLE
New Project / Blank Port List

### ISSUE THREAD

**Issue by beingobserver** [jantje/arduino-eclipse-plugin#217]
Hi.
OS X / Kepler / V 2.2 / Arduino 1.5.7.
I am creating a project and choosing "Arduino Mega or Mega 2560" but there is not anything at Port List.

What could be the problem?

Thanks.

**Comment by beingobserver** [comment]
It is solved when i uncheck "Disable RXTX" option from Preferences.

**Comment by jantje** [comment]
sounds like how it should work.
