### ISSUE TITLE
"Make" problem.

### ISSUE THREAD

**Issue by beingobserver** [jantje/arduino-eclipse-plugin#218]
Hi. (OS X / Kepler / Arduino 1.5.6 r2 / V2.2)

Why i am getting this error?

4:57:43 **** Incremental Build of configuration Release for project TestProject ****
make all 
Cannot run program "make" (in directory "/Users/myComputer/Documents/workspace/TestProject/Release"): error=2, No such file or directory
14:57:43 Build Finished (took 21ms)

Thanks.

**Comment by rlogiacco** [comment]
Bad combination of plugin version and Arduino IDE? Have you checked the website if that's an acceptable pair?

**Comment by beingobserver** [comment]
Web site is too complicated. Can you give me a link which shows the appropriate combinations?
Thank you.

**Comment by jantje** [comment]
>Web site is too complicated. Can you give me a link which shows the appropriate combinations?

Nice compliment.
Basically my thought: If install->start here->mac is to complicated for you .... stick to the arduino IDE.
No thanks
Jantje
