### ISSUE TITLE
symbols tab missing

### ISSUE THREAD

**Issue by GoGunner** [jantje/arduino-eclipse-plugin#228]
Using Juno & plugin 2.4.0.201502210217
Previously was a V1 user so don't know if the functionality was removed or other.
Properties > C/C++ General > Paths and Symbols >  no longer add the Symbols tab on new projects.
![prop_paths_and_symbols_nosym](https://cloud.githubusercontent.com/assets/5829958/6346132/bcbb2c46-bbd2-11e4-863e-d3f2cee75070.PNG)

**Comment by jantje** [comment]
@GoGunner 
Only the Arduino section is under control of the arduino eclipse plugin.
Is it this you are looking for?
![screenshot-properties for batterijlader](https://cloud.githubusercontent.com/assets/1175841/6346662/3c5b386c-bc12-11e4-967d-bc100b3c3514.png)

**Comment by GoGunner** [comment]
As I can see it was at both places with the Symbols tab information being piped over to the CDT Managed Build Setting Entries [Shared], which was not editable.  I take it then that this is the new behavior and access point with the Symbol tab not being a part of it?  From the previous release I had expected it in the Symbols tab.   It doesn't seem to be the standard behavior one might expect, especially someone that is migrating over from V1 or C++.
![prop_paths_and_symbols_sym](https://cloud.githubusercontent.com/assets/5829958/6347633/07c5cb22-bbdf-11e4-84bd-9d244eaf0cb2.PNG)

**Comment by jantje** [comment]
I'm not quite following?
I assume your problem is fixed. So I'm closing the issue. If i misunderstood please reopen.
