### ISSUE TITLE
C/C++ with Arduino core libs

### ISSUE THREAD

**Issue by omes22** [jantje/arduino-eclipse-plugin#231]
Could You please make a "How to" for useing this IDE and the Arduino core libs via C/C++? My problem is that some Arduino core libs are not working corectly in a C/C++ project.
I get 47 Errors in a simple blink example:

![eclipse_ide](https://cloud.githubusercontent.com/assets/10197163/6639193/c41499f0-c98d-11e4-8e93-5f1d8b7e9e46.png)

**Comment by jantje** [comment]
Have you seen the how to's at  http://eclipse.baeyens.it ?
Have you seen the faq http://eclipse.baeyens.it/faq.shtml#/troubleshooting Eclipse tells me there are bugs in my code but it compiles ok.

**Comment by omes22** [comment]
Solved. 

Thank You very much :-)
