### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by sk8nfool** [jantje/arduino-eclipse-plugin#237]
The "Watch a video ..." link on http://www.baeyens.it/eclipse/index.html tosses a 404 error

**Comment by jantje** [comment]
txs for the info.
The real link is http://www.baeyens.it/Media/eclipse/index.html 
Note that the movie is getting outdated.
Best regards
Jantje

**Comment by jantje** [comment]
or http://www.baeyens.it/eclipse/serial_demo.wmv

**Comment by sk8nfool** [comment]
I noticed it was getting dated but it did help.

**Comment by jantje** [comment]
Good that it helped.
I reopen as the link still is not working

**Comment by jantje** [comment]
now fixed
