### ISSUE TITLE
Errors when openig Window/Prefs/General/Appearance/Colors and Fonts

### ISSUE THREAD

**Issue by sk8nfool** [jantje/arduino-eclipse-plugin#240]
Opening Window/Preferences General/Appearance/Colors and Fonts pops a window stating an Argument Error has occurred. It also says to look at the error log for details but doesn't tell me where this log resides!

**Comment by jantje** [comment]
See http://eclipse.baeyens.it/faq.shtml#/troubleshooting
How can I find out more of the problem at hand?

**Comment by jantje** [comment]
have you more input for me?

**Comment by jantje** [comment]
No more input received so closing
