### ISSUE TITLE
"Add Library" option does not indicate previously added libraries

### ISSUE THREAD

**Issue by riban-bw** [jantje/arduino-eclipse-plugin#247]
The "Add a library to the selected project" menu option shows a dialog that allows the user to select tick boxes to choose which libraries to add. It would be advantageous if these tick boxes showed the currently added libraries and allowed their removal by deselection.

**Comment by jantje** [comment]
Indeed i would be nice. But it is also a lot of work.

**Comment by riban-bw** [comment]
Pull request #266 adds feature to show libraries currently in project. I am almost finished patch to remove unselected libraries. I hope to test and create pull request tomorrow.

**Comment by riban-bw** [comment]
Checked with today's nightly and it works fine.

**Comment by jantje** [comment]
cool. I still need to test. Txs
