### ISSUE TITLE
sample sketch: shows files which are located in folder, but not meant as sketch

### ISSUE THREAD

**Issue by jipp** [jantje/arduino-eclipse-plugin#248]
I use the plugin on OSX.
when browsing though and selecting Example code I see files like:
-.DS_Store (OSX specific)
-readme.txt
-Temboo

they cannot be selected as they have nothing to do with examples - which is OK, but confusing.

I can propose a fix and can generate a pull request if this is ok.

**Comment by jantje** [comment]
please generate a pull request.

**Comment by jantje** [comment]
fixed
