### ISSUE TITLE
avrdude pop-up shows "no name provided"

### ISSUE THREAD

**Issue by riban-bw** [jantje/arduino-eclipse-plugin#251]
During upload of firmware to Arduino, the pop-up shows the text, "no name provided". What does this mean? Is there a way to specify what text is shown?

**Comment by jantje** [comment]
can you show me an image?

**Comment by riban-bw** [comment]
Screenshot attached.
![averdude](https://cloud.githubusercontent.com/assets/3158323/7476091/521ed196-f343-11e4-8664-1d71f8dc37d7.png)

**Comment by jantje** [comment]
Och I see
That is probably something in the code that was not assigned a value.
I don't think there is a way to change the text without coding.

**Comment by riban-bw** [comment]
UploadSketchWrapper.java:155 looks up an build environmental variable which is empty so uses default text, "no name provided". I can't figure out what this line of code is trying to do. Replacing it with:
```
monitor.beginTask("Uploading \"" + myProject.getName() + "\"", 2);
```
gives a more useful message in the dialog.

**Comment by jantje** [comment]
should be fixed as requested. please reopen if fix doesn't work.
