### ISSUE TITLE
Using programmer "USBTinyISP"

### ISSUE THREAD

**Issue by karunadheera** [jantje/arduino-eclipse-plugin#253]
Hi there,
Cannot continue in project settings without selection of a Serial Port. USBTinyISP has no serial port because it is not a USB to Serial converter. I have this working fine on Arduino IDE. I really like when my favourite comprehensive IDE (Eclipse) can be used to write Arduino Code.

How to make this plugin work with USBTinyISP?

Thanks,
PK.

![screen shot 2015-05-11 at 22 45 55](https://cloud.githubusercontent.com/assets/1218348/7564995/84fde3d6-f82f-11e4-8f11-41bd02a69010.png)

**Comment by jantje** [comment]
Just fill in "something".
It should work fine

**Comment by jantje** [comment]
did that fix it?

**Comment by riban-bw** [comment]
This issue is also described in issue #264 and fixed by pull request #268 so should be able to close this.

**Comment by jantje** [comment]
@riban-bw 
indeed
