### ISSUE TITLE
Javadoc error in Common.java

### ISSUE THREAD

**Issue by riban-bw** [jantje/arduino-eclipse-plugin#259]
There is a parameter missing from the javadoc for function getBuildEnvironmentVariable in Common.java. At line 485 there should be a description of the second parameter "configName" something like this:
```
     * @param configName
     *            the project configuration to use
```

**Comment by jantje** [comment]
feel free to correct and make a pull request.

**Comment by riban-bw** [comment]
Pull request submitted (#261)

**Comment by jantje** [comment]
pull request accepted
