### ISSUE TITLE
Arduino Due on Windows build fails

### ISSUE THREAD

**Issue by real-artswan** [jantje/arduino-eclipse-plugin#262]
It adds extra slash ("/") at the start of value A.BUILD.VARIANT.PATH each time on reparsing config files so I've got path like "/D:/Install/arduino-1.5.7/hardware/arduino/sam/variants/${A.BUILD.VARIANT}" and build fails. However if I go to Project Properties->C/C++ Build->Environment and fix the value all is ok
arduino 1.5.7
eclipse nightly bundle win64.2015-05-17_02-06-59.tar.gz

**Comment by jantje** [comment]
Do you also have the issue with 1.6.1 and the latest nightly build?

**Comment by real-artswan** [comment]
Checked with build 2015-05-26 and arduino 1.6.1. Works well. Thanks you

**Comment by jantje** [comment]
cool txs.
