### ISSUE TITLE
Serial port required in new sketch (project) wizard

### ISSUE THREAD

**Issue by riban-bw** [jantje/arduino-eclipse-plugin#264]
The new sketch (project) wizard will not enable the "Finish" button until a serial port name is entered. The development host may not have a serial port. A work-around is to manually enter any text in this box but it seems inappropriate to check there is text in the box but not check its validity.

**Comment by riban-bw** [comment]
Fixed in nightly. Works fine for me - cheers.

**Comment by jantje** [comment]
indeed.
