### ISSUE TITLE
Cannot add a board that is not on board.txt (Intel Edison)

### ISSUE THREAD

**Issue by sylvioalves** [jantje/arduino-eclipse-plugin#269]
Hi, 

Arduino IDE 1.6.4 added the Board Manager, which allows downloading new boards like Intel Edison.
However, after downloading this new component,  the board.txt file is not updated and Eclipse cannot see this board.

Is there any way to add it manually?

Thanks.

Sylvio

**Comment by jantje** [comment]
1.6.4 is not supported.
http://eclipse.baeyens.it/installAdvice.shtml

**Comment by sylvioalves** [comment]
Oops.. Of course! Thanks.
