### ISSUE TITLE
Upload is done also when build fails

### ISSUE THREAD

**Issue by FredericG-BE** [jantje/arduino-eclipse-plugin#284]
When the option is selected to automatically build before uploading, the load is also done when the build fails. The fact that the build failed is far from obvious.

**Comment by jantje** [comment]
I know. I didn't find a way to know the build failed.
I'm open to suggestions.

**Comment by FredericG-BE** [comment]
Is there a possibility to show a dialog box at the end of the build when the build fails?

**Comment by jantje** [comment]
If I can find a way to know the build failed

**Comment by jantje** [comment]
@infthi 
I tested this today and it works fine :-)
