### ISSUE TITLE
Import dialog: when pasting in a path, still have to opendialog to get the path accepted

### ISSUE THREAD

**Issue by mattbsoftware** [jantje/arduino-eclipse-plugin#29]
env: Mac Mountain Lion (10.8.4), Eclipse Juno (Service Release 2 Build id: 20130225-0426)

Steps: 
1. right click project
2. import 
3. choose library path 
4. paste in a legit path, leave the edit with the legit path
5. finish does not become enabled
![screen shot 2013-07-25 at 11 44 00 pm](https://f.cloud.github.com/assets/106705/860622/8e21d898-f5af-11e2-8c13-c43db3a9618f.png)

work-around:
1. right click project
2. import 
3. choose library path 
4. paste in a legit path, leave the edit with the legit path
5. click browse
6. click Open on the file open dialog
5. finish is enabled

**Comment by jantje** [comment]
as the arduino library import has been completely rewritten this is no longer an issue.
