### ISSUE TITLE
Paste of path into Import source folder doesn't trigger "Finish"

### ISSUE THREAD

**Issue by nkolban** [jantje/arduino-eclipse-plugin#295]
When I open the dialog for "Add a source folder to the selected project" and then paste a path into the "Source Folder Location" text field, that action does not trigger the "Finish" button.  However if I type the same text, it does.  I believe that the code needs to be modified to detect a paste into the text field and perform validation on that action.

**Comment by jantje** [comment]
The "Add a source folder to the selected project"  is actually an elder of the "import libraries". I hardly use it anymore.
But feel free to improve :-)
Best regards 
Jantje
