### ISSUE TITLE
The include order of ino files should have the project ino first

### ISSUE THREAD

**Issue by lakidd** [jantje/arduino-eclipse-plugin#298]
http://forum.arduino.cc/index.php?topic=79595.msg2365354#msg2365354

**Comment by jantje** [comment]
I changed the order so that if a .ino file exists with the same name as the project it is included first.
Should be available from tomorrow with the nightly.

**Comment by lakidd** [comment]
Fixed ! Thanks

**Comment by jantje** [comment]
cool :-)
