### ISSUE TITLE
Missing LINK_OBJ for .ino and .pde sources in subdir.mk

### ISSUE THREAD

**Issue by Louis2016** [jantje/arduino-eclipse-plugin#303]
Hi,

With nightly build 2.4 and every other version, it isn't possible to build project with .ino or .pde files.
Even if .ino and .pde are declared as C/C++ files, they are ignored by make.
subdir.mk is created but it lacks an "LINK_OBJ" entry for the corresponding .o object file and thus the compilation command is never executed.

Regards

**Comment by jantje** [comment]
It works fine on linux.
Have you read this blog on how it works?
I explain that .ino and .pde files are not processed in the make file and how it works.

**Comment by Louis2016** [comment]
Yes. But .ino.cpp is not created. subdir.mk is created with .ino not .ino.cpp. LINK_OBJ is missing. As a result, .ino are not compiled.

Workarounds:
- renaming .ino to .cpp works
- adding LINK_OBG to subdir.mk and unsetting automatic makefile generation also works

So?

**Comment by Louis2016** [comment]
All tests under window 7 32 bits.

**Comment by jantje** [comment]
just wondering
Are you using the cdt build command or the arduino verify command?

**Comment by Louis2016** [comment]
I'm using the CDT build command (didn't know about the arduino verify command, will try it and let you know)

**Comment by jantje** [comment]
Now I remember this is a duplicate of #191
