### ISSUE TITLE
Platform.txt Error

### ISSUE THREAD

**Issue by DQvsRA** [jantje/arduino-eclipse-plugin#307]
When i try to start new project i get this error message
![screenshot from 2015-09-19 17 47 30](https://cloud.githubusercontent.com/assets/442111/9976764/87a0df70-5ef6-11e5-8218-a526a011c05e.png)

**Comment by jantje** [comment]
I've seen somethng similar before but I can not recall the root cause.
Which arduino IDE version and plugin version are you using?

**Comment by DQvsRA** [comment]
I use 
Eclipse IDE for C/C++ Developers
Version: Mars Release (4.5.0)
Build id: 20150621-1200

Actually this problem does not effect on project.

**Comment by jantje** [comment]
Which version of the plugin are you using? 
Which version of the Arduino IDE are you using?
Are you using Teensy?

**Comment by jantje** [comment]
closing as to long open without input
