### ISSUE TITLE
Can't access: http://www.baeyens.it/eclipse/v2

### ISSUE THREAD

**Issue by mdilger** [jantje/arduino-eclipse-plugin#310]
Hi, I am trying to set up Eclipse as per Neil Kolbans instructions of 2015-06-28

For some reason Eclipse can't find http://www.baeyens.it/eclipse/v2

Any ideas??

Also, I am happy to be a tester once I get everything running.  FYI, I am working with Uno, Due and esp8266.  Time for a more powerful IDE.

Cheers,
Mike

**Comment by mdilger** [comment]
Sorted.  I had an internet issue.

**Comment by jantje** [comment]
good :-)
For the testing. Please fil out this form. https://docs.google.com/forms/d/12laG01sOcWG23Zaixur4v31MFcZ66ObJL_8XvRVgZZA/viewform
Jantje

**Comment by mdilger** [comment]
done, earlier. Cheers, Mike

**Comment by jantje** [comment]
:-)

**Comment by jantje** [comment]
Och yes
There are a couple of people subscribed with a wrong email address. If you didn't receive a google groups invite yet .... well you may be one of them.

**Comment by mdilger** [comment]
Thinking about it,  I may have got distracted at "work" earlier today and not submitted the form.  Anyway, I have just completed the form again.  Cheers, Mike.
