### ISSUE TITLE
The cdt build command does not generate the .cpp.ino file

### ISSUE THREAD

**Issue by jantje** [jantje/arduino-eclipse-plugin#311]
The creation of the .cpp.ino file is only done when using the verify button.

**Comment by jantje** [comment]
If you click upload it starts a build but it does not generate the .ino.cpp file

**Comment by wimjongman** [comment]
Ah, yes. The builder framework :sunglasses: 

I also saw that you played with (or already implemented) the refactoring participation?

**Comment by jantje** [comment]
>Ah, yes. The builder framework :sunglasses:

I took me some hard work to find/understand/implement/make it work. But the result it great

>I also saw that you played with (or already implemented) the refactoring participation?

I have no clue what you are talking about
