### ISSUE TITLE
Can't start project

### ISSUE THREAD

**Issue by DQvsRA** [jantje/arduino-eclipse-plugin#312]
Hello
OS: Windows 7
Eclipse: Mars 4.5
Arduino: 1.6.5
Hardware: Arduino Nano
Arduino-Eclipse: installed from market.

I can't even create a project. 

![1](https://cloud.githubusercontent.com/assets/442111/10160935/c52c41be-66b1-11e5-93e6-bdd211f39972.png)
![2](https://cloud.githubusercontent.com/assets/442111/10160941/c9f102ac-66b1-11e5-97d7-5e75223cb8ee.png)

**Comment by DQvsRA** [comment]
The same thing when i install from nightly.
P.S. My Arduino Folder is not in default path, i don't install any programs on C drive

**Comment by jantje** [comment]
I have checked in change to investigate this issue.
Can you update your plugin tomorrow and try again?

**Comment by jantje** [comment]
has the change helped you?

**Comment by DQvsRA** [comment]
Actually i tune and prepare eclipse to work with "AVR for eclipse" with .h files from Arduino core and it's work fine.
