### ISSUE TITLE
Problem with ESP8266/Arduino and Eclipse

### ISSUE THREAD

**Issue by lrmoreno007** [jantje/arduino-eclipse-plugin#316]
Hi, i'm using Eclipse/Arduino to program a ESP8266/Arduino, everithing go OK except when upload with esptool.

Eclipse don't get the parameter: tools.esptool.upload.params.verbose = -vv   established in platform.txt

To make it run OK, I must add a new line in platform.txt with a generic " upload.verbose = -vv ".  But this can affect to other upload tools. 

Why eclipse don't read this parameter? how to solve?

Thanks in advance.

P.D.: this is the pull request in ESP8266/Arduino ... https://github.com/esp8266/Arduino/pull/781

**Comment by jantje** [comment]
I responded in the esp thread. I think there is a problem in the platform.txt file
https://github.com/esp8266/Arduino/pull/781

**Comment by lrmoreno007** [comment]
Thanks

**Comment by jantje** [comment]
:-)

**Comment by jantje** [comment]
If you think there is nothing to fix in the plugin can you close this issue?

**Comment by lrmoreno007** [comment]
Continue in esp8266/Arduino#781
