### ISSUE TITLE
Arduino IDE Path can't be found

### ISSUE THREAD

**Issue by heathhes** [jantje/arduino-eclipse-plugin#318]
I am using:
MAC OS El Capitan
Arduino 1.6.5
Eclipse IDE for C/C++ Developers
      Version: Mars.1 Release (4.5.1)
      Build id: 20150924-1200
Java 8 update 65

The problem is that when I go to select where the Arduino IDE is located ( /Applications/Arduino-1.6.5)
in the Eclipse Preferences   (Eclipese -> Prefernces-> Arduino), the Arduino path IDE will not recognize the path.  I get the error "Arduino folder is not correct!".  Several other people have also had this problem on the Arduino Forum.

**Comment by jantje** [comment]
Have you seen this? http://trippylighting.com/teensy-arduino-ect/arduino-eclipse-plugin/arduino-eclipse-ide-2-4-arduino-1-6-3-teensyduino-1-22-mac-windows-installation/

**Comment by TrippyLighting** [comment]
BTW, two Mac users on the Teensy forum have recently confirmed that my instructions also still work with the newest releases of Teensyduino and the Arduno IDE.

**Comment by heathhes** [comment]
I see the links for the Teensy but it does not relate to my issue. Here is the link (http://forum.arduino.cc/index.php?topic=345878.new#new) to the Arduino forum where others are having the same issue as well.

**Comment by jantje** [comment]
I think you are using the latest stable and missed this 
"In the 1.5 series there has been a change in the folder structure on mac from arduino IDE 1.5.7 onwards. See this issue for more detail. "
in the mac part of this page http://baeyens.it/eclipse/installAdvice.shtml
see #180

**Comment by heathhes** [comment]
Ok, there seems to be an issue with post Arduino 1.5.7 path. I am not super savy when it comes to this typed of issue.  Is there anyway you could make it more clear on how to correct the issue? I have reviewed the installAdvice #180, but I can't figure out what to do. If you could make it more obvious what to do to make it more clear to correct the issue I would be glad to share this information via a small tutorial and also contribute some $ to the Eclipse Arduino plugin (assuming it works).  Thank you very much for your time and effort.  I am really hoping I can sort this out.

**Comment by TrippyLighting** [comment]
There is no issue with the post 1.5.7 path. If you would actually bother to really follow the steps provided in the installation tutorial and use the download links in the tiutorial I provide on my blog http://trippylighting.com/teensy-arduino-ect/arduino-eclipse-plugin/arduino-eclipse-ide-2-4-arduino-1-6-3-teensyduino-1-22-mac-windows-installation/
It will work.
Today I loaded down and installed  the most current Arduino 1.6.5 IDE and the most recent NIGHTLY build of the Arduino Eclipse IDE and it worked out of the box. This works with Teensyduino and without.

**Comment by jantje** [comment]
@heathhes 
like @TrippyLighting is stating: use the nightly build of the arduino eclipse plugin.

**Comment by jantje** [comment]
Closing assuming this is a usage error.
