### ISSUE TITLE
Arduino IDE 1.6.6 boards manager is not compatible with the nighty on windows and V2.4 of the plugin

### ISSUE THREAD

**Issue by jantje** [jantje/arduino-eclipse-plugin#322]
Arduino IDE 1.6.6 installs the board info on a different location than 1.6.5
As such the plugin does not find newly installed boards.

**Comment by jantje** [comment]
Seems the  dump file creation doesn't work on my system as well. So ... Forget about 1.6.6 for now

**Comment by universpharmacie** [comment]
Although I tend to be an early adopter, I will refrain from updating to 1.6.6 for the moment. Thank you for the hint!

**Comment by jantje** [comment]
Found issues in linux as well.

**Comment by jantje** [comment]
This is one of the main reasons to fix #306 
I'm working on it :-)
