### ISSUE TITLE
/bin/sh: 1: /bin/avr-g++: not found : Error 127 

### ISSUE THREAD

**Issue by Sanchke** [jantje/arduino-eclipse-plugin#329]
Can't compile anything. I'm using arduino 1.5.1 on Debian jessie with eclipse Mars.1

**Comment by jantje** [comment]
I decided to no longer respond to github issues -and other questions- due to a lack of support.
As a patron you can post a message on the patreon forum stating you support a github issue. This allows me to support people who support me.
https://www.patreon.com/posts/3700469

**Comment by jantje** [comment]
no support from sponsors
