### ISSUE TITLE
Include ArduinoHardwareLibPath in arduino resourse folder

### ISSUE THREAD

**Issue by mattb5906** [jantje/arduino-eclipse-plugin#332]
Include linked ArduinoHardwareLibPath folder (hardware\arduino\avr\libraries) in the auto generated arduino resource folder by default. The SPI, EEPROM etc. would then work as soon as a new project is created. It took me a while to find these libraries as a new user.

**Original:**
![original](https://cloud.githubusercontent.com/assets/8330291/11626076/ca2a6766-9cd7-11e5-89e7-78e0e3479bf4.JPG)

**Suggested:**
![folder added](https://cloud.githubusercontent.com/assets/8330291/11626075/ca24970a-9cd7-11e5-802f-3a5fd85d0b4a.JPG)

**Comment by mattb5906** [comment]
Just saw the patreon thing. Will add my donation soon.

**Comment by TrippyLighting** [comment]
Awesome!

**Comment by jantje** [comment]
See http://eclipse.baeyens.it/how_to.shtml#/f on how to work import libraries.

**Comment by mattb5906** [comment]
Thanks jantje. I completely missed that :)

**Comment by jantje** [comment]
You're welcome.
