### ISSUE TITLE
Example is not copied in the project once you entered the debug page

### ISSUE THREAD

**Issue by wimjongman** [jantje/arduino-eclipse-plugin#348]
* Create a new project
* Select the blink example

Result, no file is created in the project.

**Comment by jantje** [comment]
Are you sure the checkbox was on?
I tested this several times with several sketches?
It did happen quite often I clicked the text which did not put the checkbox and then no code is added.

**Comment by wimjongman** [comment]
yes, I am sure.

**Comment by jantje** [comment]
I just tested it here and it works fine. Can you reproduce this? Is this only with a specific sample?

**Comment by wimjongman** [comment]
I made a video here:

http://screencast.com/t/xgCAiWI9

**Comment by jantje** [comment]
I can hardly believe my eyes.
Did the same thing here and it works :-(
![schermafdruk-arduino - eclipse platform](https://cloud.githubusercontent.com/assets/1175841/12302677/b4d3eb78-ba26-11e5-85a1-7d22064d7f30.png)
Is there anything in the error log?

**Comment by jantje** [comment]
got it
It seems that it doesn't work when you also show the debug page.
What movies are good for :-)

**Comment by jantje** [comment]
If you go through to debug and go back you will find that your example selection is gone.
That is the reason why there is no code added.
Now I need to find out why the sample program gets deselected???

**Comment by jantje** [comment]
I think it is a eclipse root cause. 
As the list of examples is dependent on the selected board I can only fill the sample page when you enter it.
I did that with this code
```java
    @Override
    public IWizardPage getNextPage(IWizardPage page) {
	// TODO Auto-generated method stub
	if (page.equals(this.mNewArduinoSketchWizardCodeSelectionPage)) {
	    String PlatformPath = NewArduinoSketchWizard.this.mArduinoPage.getPlatformFolder().toString();
	    NewArduinoSketchWizard.this.mNewArduinoSketchWizardCodeSelectionPage.setPlatformPath(PlatformPath);
	}
	return super.getNextPage(page);
    }
```

Apparently when you go from the sample selection page to the debug page this code gets called again.
I'll fix it with a optimalisation (only update when the platformpath has changed)

**Comment by jantje** [comment]
This is not a 3.0.0 problem only.
thanks for finding this bug wim. I wouldn't have found it without your video.
