### ISSUE TITLE
Update sites are not correct

### ISSUE THREAD

**Issue by wimjongman** [jantje/arduino-eclipse-plugin#356]
* Update sites still point to luna
* Update site points to the nightly repo

Proposed fixes:

* Point to mars
* Point to release update site
* Add nightly site to repos but as an inactive site.

**Comment by wimjongman** [comment]
New update site required:

http://www.baeyens.it/eclipse/V3

**Comment by jantje** [comment]
I would keep on using V2.

**Comment by wimjongman** [comment]
Let's not take shortcuts and make a v3

Xcss 4 brvty mbl

**Comment by wimjongman** [comment]
I am back at my laptop.

I am not sure why you want to keep using V2 but since the software is now
on V3 it is not logical to keep using V2. If you do not want to maintain a
version repo then lets call it release or something like that.

Cheers,

Wim

**Comment by jantje** [comment]
ok you win

**Comment by TrippyLighting** [comment]
V3

It's easier to ask for forgiveness than to ask for permission ;-)

**Comment by lrmoreno007** [comment]
Too many demands on the work of others :(

**Comment by jantje** [comment]
V3

**Comment by jantje** [comment]
@wimjongman 
Can you create the V2.4 branch I forgot to create? I'm really bad at git :-(
@TrippyLighting and @lrmoreno007 
Are you aware there is also a developers mailing list? eclipse-arduino-dev@freelists.org

**Comment by wimjongman** [comment]
There is already a 2.4 tag. I will make a 2.5

**Comment by wimjongman** [comment]
Fixed. See also #389
