### ISSUE TITLE
indexer will not start

### ISSUE THREAD

**Issue by nicoverduin** [jantje/arduino-eclipse-plugin#362]
I just downloaded the overnight build (28-1) on Windows7. Looks great!!!. However the indexer does not seem to start.

**Comment by jantje** [comment]
I experianced this problem as well and I'm looking for a solution.
Open and close the project (not eclipse) to get it running again.
Does not always work....

**Comment by nicoverduin** [comment]
I'll check monday. Have this  installation at work :)

**Comment by jantje** [comment]
Och you have work? and you use the plugin at work?
coool

**Comment by nicoverduin** [comment]
Unfortunately Feb is my last month. And since I have nothing to do.... May as well hobby around.

**Comment by jantje** [comment]
a shame indeed. but good for me :-)

**Comment by nicoverduin** [comment]
yep :)

**Comment by nicoverduin** [comment]
I ran it today on my Macbook running Yosemite with 31-1-2016 version. The index still waits until I close the project and reopen it. Also when I change boards (been switching between UNO and NodeMCU 1.0) I have to close the project the first time. From then on it seems to work every time.

**Comment by jantje** [comment]
is that with the very latest version?

**Comment by nicoverduin** [comment]
yep

**Comment by jantje** [comment]
grrr :-(

**Comment by nicoverduin** [comment]
mac64.2016-01-31_03-16-59

**Comment by jantje** [comment]
I just had hoped it fixed the issue. I did another fix today with spec.d which cause annoying things but the indexer never hung anymore.
So I don't know anymore what I can do to fix it.

**Comment by nicoverduin** [comment]
I'm gonna reload it in a couple of minutes

**Comment by jantje** [comment]
It may be better to wait for the fix for tomorrow so the spec.d is also fixed.

**Comment by wimjongman** [comment]
Is there a 'copy build id to clipboard' command in the quick access box?

**Comment by nicoverduin** [comment]
Well
I already did a clean installation with a new workspace. Made a simple blink program. Had to close the program to start the indexer. Then I installed the ESP8266 platform. Switched to the ESP8266. Indexer started working straight a way. So it seems to only begin at the creation of the program.

**Comment by nicoverduin** [comment]
I'll give it a shot tomorrow at work under Windows7 on my "hooker"  machine (DELL :))

**Comment by nicoverduin** [comment]
Tested the latest version today. Unfortunately no difference. I still have to close a project first to get the indexer working. Switching between platforms makes no difference.

**Comment by jantje** [comment]
@nicoverduin 
Do I understand correctly that it is better? I assume you have upgraded to the latest version so the spec.d file issue is gone?

@wimjongman 
Sorry I do not understand what you are asking.

**Comment by jantje** [comment]
I just upgraded to the latest version and I can't reproduce the indexer hanging problem here.
I'm running on linux.

**Comment by jantje** [comment]
I have been running with the nightly and this problem has disappeared for me.

**Comment by nicoverduin** [comment]
Cool
I'll give it a shot tormorrow
What was the cause apparantly?
thx

**Comment by jantje** [comment]
Well nothing has changed lately.
The only thing I changed is that instead of directly adding libraries I add libraries with a job.
If you test and it is still not working. Can you try to disable the "automatically import libraries based on includes" in windows->preferences->arduino?

**Comment by nicoverduin** [comment]
will do!

**Comment by nicoverduin** [comment]
Ok did the following:

- fresh installation with new workspace
- generated empty INO indexer **OK**
- renamed to .cpp indexer **NOK**
- close project/open project indexer **OK**
- Change to different platform indexer **OK**
- Automatic import OFF **No change in effects**

**Comment by jantje** [comment]
when you renamed to .cpp did you also delete the .ino.cpp file?

**Comment by nicoverduin** [comment]
I just prest F2 on the filename and renamed it to .cpp. Nothing deleted though.
Normally I always develop in .cpp straight away and for the customer I copy a version to a sepate folder and rename it to .ino.
In this test I started with a .ino (meaning it was a mistake) which gave me a reason to test a little more extensive.
As for priorities, Jan I can certainly live with the workaround. It is a one time effort to close and reopen the project. On the other hand I am a great disapprover of sympton solotions without knowing the cause. But if time is a limiting factor I would suggest we focus on other possibly more urgent issues. 
I am already addicted to this solution and with all the add-ons.... I think it's great.

**Comment by jantje** [comment]
>On the other hand I am a great disapprover of sympton solotions without knowing the cause. 

I am to. So I'd like to understand what is going on. I wanted a mac virtual machine for a long time. I guess it is time to set one up. Unless the .ino to .cpp rename helps me to reproduce the issue.

As to ino files. In the latest version there is no disadvantage anymore for using .ino files in the plugin.
I fixed nearly all remaining issue so there is no real other thing to focus on right now. Apart from release :-)

**Comment by nicoverduin** [comment]
Jantje
The test was at work=windows

Verstuurd vanaf mijn iPhone

**Comment by jantje** [comment]
I confirm that renaming thje last .ino file to .cpp will make the indexer hang.

**Comment by jantje** [comment]
@nicoverduin 
Can you check the issue still exists in the latest version?

**Comment by nicoverduin** [comment]
Seems to work now:
a) fresh installation
b) created .ino for UNO Indexer **OK**
c) neamed to .cpp Indexer **OK**
d) loaded ESP8266 platforms
e) Changed to ESP8266 board Indexer **OK**
f) renamed .cpp to .ino Indexer **OK**

**Comment by jantje** [comment]
:-)
