### ISSUE TITLE
org.eclipse.cdt.core.prefs overwritten when defining USBASP

### ISSUE THREAD

**Issue by francoispfister** [jantje/arduino-eclipse-plugin#364]
I need to define specific preferences in order to use an external programmer and usbasp protocol: A.UPLOAD.PROTOCOL, A.UPLOAD.PORT and A.TOOLS.AVRDUDE.UPLOAD.PATTERN are specific.
The problem is that the IDE overwrites these values even if they are modified through the project preferences editor. (Nightly build version)

**Comment by jantje** [comment]
the A.XXX values come from the boards.txt and platform.txt files. You should not change these (and other environment variables)
I'm not really sure what you are trying to achieve.
