### ISSUE TITLE
Add a save functionality to the scope

### ISSUE THREAD

**Issue by jantje** [jantje/arduino-eclipse-plugin#365]
The scope currently  does not have the possibility to dump the data for processing afterwards.
Having this possibility would be a advantage.

**Comment by jantje** [comment]
Using doubleclick on the scope could fire this.
@wimjongman 
Is there already some kind of functionality?

**Comment by wimjongman** [comment]
The scope currently does not save any state. It only knows the points currently on screen.

The view could have a button that puts the scope data in a file or something ..

**Comment by jantje** [comment]
@wimjongman 
Ok. I need this so I'm working on it.
The idea is to double click select a file and save all the points on screen.
Filtering can be done later.

**Comment by wimjongman** [comment]
Sounds like a nice feature for the new release.

**Comment by jantje** [comment]
It is handy for post processing of data
