### ISSUE TITLE
Remove CDT repo from product

### ISSUE THREAD

**Issue by wimjongman** [jantje/arduino-eclipse-plugin#388]
The CPP repo is added to the product:

>      <repository location="http://download.eclipse.org/tools/cdt/releases/8.8.1" enabled="true" />
 
 Only the main repos should be added to the product.

**Comment by wimjongman** [comment]
This was added by commit 19204ffd413472da4f21ae51ab80fb8391b182c0

**Comment by jantje** [comment]
I think I already removed it.

**Comment by wimjongman** [comment]
Yes, that was confusing. I committed the change but git said that there were no changes.
