### ISSUE TITLE
Add category to update site

### ISSUE THREAD

**Issue by wimjongman** [jantje/arduino-eclipse-plugin#389]
The repository does not have a category.

**Comment by wimjongman** [comment]
Ah, I see. You deleted the update site. I remember that I saw something flying by but I think we need to revert this. Can you explain again why you removed it?

4b9c34dd3afaf46e0e4ceb4a84e6e2a79740105e

**Comment by jantje** [comment]
Because the update site did not contain the info needed for updating the product.
On the other hand the product build also creates a update site that does contain all info at it.baeyens.arduino.product/target/repository/
So I switched to using this update site which makes the update site project was no longer used.

**Comment by jantje** [comment]
The update site never had a category by the way. All instructions to install state you have to unclick "group by category"

**Comment by wimjongman** [comment]
I see. I think we need a proper category. I will play with it a little bit.

**Comment by wimjongman** [comment]
![2016-03-13_2146](https://cloud.githubusercontent.com/assets/180969/13731262/1b5dc5d6-e965-11e5-9c8d-12b59cd90a26.png)

**Comment by jantje** [comment]
You did it :-)

**Comment by universpharmacie** [comment]
I don't know if it's in the right place here, but what about these annoying warnings about unsigned content each time when you install an update?

**Comment by jantje** [comment]
>I don't know if it's in the right place here, but what about these annoying warnings about unsigned content each time when you install an update?

fixing this costs money. lots of money.
imho the alternative (self signed) is not better

**Comment by universpharmacie** [comment]
Ah, ok, sorry. I'll already close my mouth.

**Comment by jantje** [comment]
No problem. Wim explained me less than a month ago on the developers list.

**Comment by jantje** [comment]
Wim do I need to copy  the update site now from the update site again?
Now I copy the update site from the product.

**Comment by wimjongman** [comment]
Yes from the update site. The one from the product is in raw format.

**Comment by jantje** [comment]
OK I'll fix that

**Comment by jantje** [comment]
I changed to the update site. I cleaned the whole nightly so no old things were still lingering around.
But I see 2 things I don't like:
1) The product V3 is no longer there (so people will not be able to upgrade V2.4 to V3 via the update site)
2) There are still c++ downloads in the list
![capture](https://cloud.githubusercontent.com/assets/1175841/14085804/3c73ba46-f522-11e5-9e23-89a3af753f8c.PNG)

**Comment by wimjongman** [comment]
Yes, the product include is an interesting thing. I guess it is harmless to include it in the feature. I will make the changes.

**Comment by jantje** [comment]
Should it not be a different feature?

**Comment by wimjongman** [comment]
When the product is installed in for example Eclipse CC then the user can also run it in Arduino Dev mode with -product xxxxx

**Comment by jantje** [comment]
>When the product is installed in for example Eclipse CC then the user can also run it in Arduino Dev mode with -product xxxxx

Am I missing something?

**Comment by wimjongman** [comment]
I have a hard time including the product in the update site.

**Comment by jantje** [comment]
Then forget about it.

**Comment by wimjongman** [comment]
It is not need for a V2 to V3 product upgrade. I have tested it and found no problems (apart from the fact that bash is installed on my system ;)

**Comment by jantje** [comment]
another test on bash :-) 
Maybe the test is to restrictive but given the impact I prefer it this way.

**Comment by wimjongman** [comment]
I would like the text to change so that people are more informed.

**Comment by jantje** [comment]
I'm open to suggestions.

**Comment by wimjongman** [comment]
"we have found programs in the path that might conflict with our external
builder. The conflicting programs are "xxxx" and "yyyy". The program might
still function but if you get strange build errors you know where to look"

[x] Don't show this message again

**Comment by jantje** [comment]
I finally finished the upgrade video.
Just in time ;-)
https://www.youtube.com/watch?v=h-rz2FR3H6Y
