### ISSUE TITLE
V3 None of the menus trigger when activated

### ISSUE THREAD

**Issue by zenseidk** [jantje/arduino-eclipse-plugin#400]
Hello,

Version 3 menus are not responding. I downloaded version 2.4 and updated, taking me to version 3.

When I want to go to project settings, no pop up window appears when I click Project-->Properties.
I am also unable to upload code to the board. It says no project is selected, even though I have a project open and written code.

**Comment by jantje** [comment]
If project settings is not working there is a problem in eclipse that is far more fundamental than the plugin.
Upgrading a workspace requires some thought. I'll release a video on that next week.
