### ISSUE TITLE
V3 "Automatically import libraries based on includes" setting does not get saved

### ISSUE THREAD

**Issue by compihu** [jantje/arduino-eclipse-plugin#408]
## How to reproduce:
- Start V3.0.0
- create a new workspace
- crate any arduino project (not really necessary)
- go to (menu)Window/Preferences->Arduino
- untick "Automatically import libraries based on includes"
- click Apply, then OK (or only OK)
- exit the IDE
- start the IDE again with the same workspace
- check the setting you unticked before exit -> option is active again

Tested on Linux && Windows

**Comment by jantje** [comment]
txs I'll have a look.
Any reason why you want to deactivate it?

**Comment by compihu** [comment]
Thanks,
The reason is that I use custom/modified/bugfixed versions of libraries included in the project tree as git subtrees.
You can take a look at it @ https://github.com/compihu/gate433 - fairly complex project layout

**Comment by jantje** [comment]
You should use the import source code for that. Use another folder then libraries as that folder is maintained by the plugin.

**Comment by compihu** [comment]
I have a shared virtual folder for the libraries named **"libs"** so there is no name collision either with the old **"Libraries"** nor the new **"libraries"**. The problem is that the names of the include files are the same as in the "stock" libraries, so the plugin "helps" me adding the default libraries to my project which I have to avoid.

Btw adding "**Automatically\ import\ libraries=false**" line to  **{WORKSPACE}/.metadata/.plugins/org.eclipse.core.runtime/.settings/it.baeyens.arduino.prefs** works it around until some other action removes or changes it to true (happened few times while tried to find a workaround)

**Comment by jantje** [comment]
txs for the workaround.

>I have a shared virtual folder for the libraries named "libs" so there is no name collision either with the old "Libraries" nor the new "libraries". The problem is that the names of the include files are the same as in the "stock" libraries, so the plugin "helps" me adding the default libraries to my project which I have to avoid.

I think we are talking about different things.

**Comment by jantje** [comment]
I confirm this is not working as designed.

**Comment by jantje** [comment]
This is a really old issue.
Hardware libs overwriting private ones is by design.

**Comment by Mick59** [comment]
Thanks for the answer.

The problem is that in this way Eclipse is too locked for my needs. Not
easy to tweak some Arduino libs without renaming them.
It would be really useful if the library and core directories in the
project directory got the priority.

Regards,
Michael




Le 21 août 2017 8:45 PM, "jantje" <notifications@github.com> a écrit :

This is a really old issue.
Hardware libs overwriting private ones is by design.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/Sloeber/arduino-eclipse-plugin/issues/408#issuecomment-323821124>,
or mute the thread

**Comment by jantje** [comment]
If you want to overrule you can always use the "add source code to the project".
Once a header is found Sloeber will no longer add the lib.
