### ISSUE TITLE
V3 No private library available when more than one path in the "Private Library path" preference setting

### ISSUE THREAD

**Issue by nafep** [jantje/arduino-eclipse-plugin#409]
When having **more than one** path as "_Private library path_" in the plugin's general preferences, none of the libs in those folders is available for selection in the "_Add a library to the selected project_" list after having quit and restarted Eclipse. (Everything works fine with only one path.)

[Workaround] To make the private libraries available again, it suffices (once per Eclipse session) to go to Preferences>Arduino and press "OK". (Note that the names of the private library folders are still there; there's no need to type them in again.)

Tested on a Mac.

**Comment by jantje** [comment]
The multi private library functionality is one of my favourite additions (using multiple version control systems at the same time) so I tested this one right away and it works fine on windows.
Do you see any errors in the error log?

**Comment by nafep** [comment]
The error log is desperately empty.

**Comment by jantje** [comment]
Wierd
As I don't have a mac, it is working on windows and we have no logging; I need someone else to debug on a mac to find the root cause.

**Comment by nafep** [comment]
Okay, understood. 
I tried to take a look at the code by myself, compiling it according to your description, but I'm unfortunately way too incompetent to solve the issue.
Although I might continue giving it a shot once in a while, I guess we'll be at least two waiting for someone who can reproduce and solve the issue. I'll be using the workaround in the mean time. 
Thanks for your support and the great plugin!

**Comment by EdwinCroissant** [comment]
I am on the nightly build with Windows 10 and had the same problem until today.
It looks like the last change fixed it for me. Thank you for your good work :)
