### ISSUE TITLE
Use users folder (libraries/hardware) relative path when possible.

### ISSUE THREAD

**Issue by far5893** [jantje/arduino-eclipse-plugin#438]
In" Arduino Settings for this workspace",
file dialog does not permit to choose path (library/hardware) , relative to HOME folder or workspace.
Instead use absolute path.

In conjunction with CVS (or simply workspace folder copy) there are a lot of absolute references to change in projects config files.

(I'm using esp8266  json package manager on MARS.2)

**Comment by jantje** [comment]
duplicateof #34

**Comment by far5893** [comment]
#34 three years ago......bad news!!

**Comment by wimjongman** [comment]
> #34 three years ago......bad news!!

The good news is that we are accepting quality patches!!

**Comment by jantje** [comment]
I also posted the 6th of jan (this year) that I think I found a solution to fix it.
But nobody responded.

**Comment by far5893** [comment]
I found broken link so i not consider it.

**Comment by jantje** [comment]
>I found broken link so i not consider it.

I would consider reporting the broken link as constructive.
(Feel free the fill in the rest)
No thanks
