### ISSUE TITLE
The .ino.cpp file is no longer updated during the built.

### ISSUE THREAD

**Issue by EdwinCroissant** [jantje/arduino-eclipse-plugin#441]
You’re doing an excellent job and I’m sorry to bother you with the trivial problem I’m experiencing :) 
I’m on the nightly with Win10 and somewhere between April 12th and April 15th the .ino.cpp file is no longer updated during the built. My work around at the moment is to declare the functions before calling them. Probably I broke something but I don’t know what. Any hints will be appreciated.

**Comment by jantje** [comment]
I checked here and it is indeed broken.
I have no clue what caused this.
Workaround is to remove the generated.ino.cpp do a clean and rebuild.
Not nice
Are you sure about the time frame?. I ask as I do not see changes in this time frame in this area.
Thanks for letting us know.

**Comment by EdwinCroissant** [comment]
Thank you for checking this. Your work around is much better :) I checked the dates and found an updated .ino.ccp file dated April 14th and another one dated April 15th that was not updated. The difference is also in the file timestamp with the one from the .ino file after a build. I normally update eclipse before I start programming. But if I didn’t this could have started earlier. Good luck!

**Comment by jantje** [comment]
I had another look at this and it works in my debugging environment but it does not work in my production environment :-(
I have no clue what is going on here.

**Comment by EdwinCroissant** [comment]
I don’t know if this is related:

After the last update I was greeted with a java zero pointer exception.  In my current project the SD library attached itself and removing this library was not possible as the Finish button of the Add a library to the current project dialog stopped working.  I recovered by removing the offending entries in the linked resources and the include folders of the Arduino C++ and Arduino C compiler of the project properties. After that the java zero pointer exception was gone and I could build the project as normal.

Beside this your project rocks :)

Maybe this helps :)

**Comment by jantje** [comment]
One of the latest changes added the programmers. This means the programmer is not filled in. That can cause the null pointer.
The standard upgrade procedure fixes that. The standard upgrade procedure is described here. http://eclipse.baeyens.it/how_to.shtml#/n
Once done the standard upgrade procedure and it still doesn't work we talk about regression or a bug.

**Comment by i-copter** [comment]
Deleting the .ino.cpp file seemed to work for me.  

Mac OS X version nightly build 27-Apr-2016

Thanks.

**Comment by EdwinCroissant** [comment]
Thank you jantje, forgot about that one, saved my day for the my other projects :)

**Comment by jantje** [comment]
This one is fixed on my system.
Anyone on the latest nightly still has this problem?

**Comment by EdwinCroissant** [comment]
It works again! Thank you :+1: !

**Comment by jantje** [comment]
txs for the feedback
