### ISSUE TITLE
How to restore Serial Monitor's CLEAR button?

### ISSUE THREAD

**Issue by adamryczkowski** [jantje/arduino-eclipse-plugin#446]
When I run ArduinoEclipse stand-alone product, the Serial Monitor is lacking much of its functionality. In particular there is no way to clear its contents: 
![arduinoeclipse v3 product](https://cloud.githubusercontent.com/assets/4469707/15183832/172ed50c-1793-11e6-98b9-e2c73989de44.png)

For reference, this is what I can see on the Serial Monitor, when I installed Arduino IDE V3 over already existing Eclipse installation:
![arduino ide v3 installed over eclipse](https://cloud.githubusercontent.com/assets/4469707/15183846/22c13fea-1793-11e6-8c58-8cbf1e1b03e8.png)

**Comment by adamryczkowski** [comment]
OK. I found the solution myself, sorry for taking your time.

The answer to those missing buttons is in those small toolbar icons on the top of SerialMonitor window, just beside the "+" and "x" buttons...

**Comment by jantje** [comment]
good work :-)

**Comment by adamryczkowski** [comment]
No. It is your work that is truly awesome. Thank you!
