### ISSUE TITLE
Doesn't find Java 1.8 OS X

### ISSUE THREAD

**Issue by trevorsmedley** [jantje/arduino-eclipse-plugin#481]
Hi,

Just trying to get the eclipseArduino app up and running, and I get the error:  Version 1.6.0_65 of the JVM is not suitable for this product. Not sure if this is the right place to ask this question or not, but figure it's worth a try.

I have Java Version 8 Update 73 installed (this is what Safari shows, for example, when I test my java version using https://www.java.com/verify/). I also have the "legacy" JVM 1.6 installed, which is what seems to be causing the problem.

How can I get eclipseArduino to see the new Java version rather than the old?

Thanks, Trevor

**Comment by trevorsmedley** [comment]
Never mind. It's an issues with Eclipse looking for Java Developer Kit version, rather than the runtime. Resolved.

**Comment by jantje** [comment]
thanks for the good work :-)
