### ISSUE TITLE
V3 Doesn't Show up

### ISSUE THREAD

**Issue by bigdman1216** [jantje/arduino-eclipse-plugin#494]
I have downloaded the plugin but there are no menus and the preferences page does not show "arduino" as an option.  I had a v2 version but cannot revert back.  Is there a V3 install guide that I can follow, I didn't see one?  
Also I can move to any arduino version necessary. 
Thanks!
![eclipse_vrsn](https://cloud.githubusercontent.com/assets/5958322/16532169/108cf30e-3f85-11e6-833b-acd295749149.png)

**Comment by jantje** [comment]
Have you activated the arduino perspective?

**Comment by bigdman1216** [comment]
Yes, its empty.  Before when I had V2 I could get through everything except the upload would fail.  I figured it was something to do with my IDE version as per[http://eclipse.baeyens.it/installAdvice.shtml](url)
![ard_perspective](https://cloud.githubusercontent.com/assets/5958322/16532918/04599308-3f8a-11e6-92d0-73debd37b50a.png)

**Comment by jantje** [comment]
What eclipse version do you run?

**Comment by bigdman1216** [comment]
Mars 4.5.2.  Should I download the full product?  Can I overlay my PyDev work on that build?

**Comment by jantje** [comment]
>Mars 4.5.2

This should be fine

> Can I overlay my PyDev work on that build?

yes (if you need mars take the stable product; the nightly is based on neon)

Don't you see errors in the error log? Something is seriously wrong in your install

**Comment by bigdman1216** [comment]
I downloaded the stable plugin here:  http://www.baeyens.it/eclipse/V3 but it doesn't show.  I am downloading the product version but I have ROS stuff that I'd prefer not to have to do all over again.  
where would I see this error log?  Usually I'll look at the console output to see the issues/warnings/errors.  What else can I show to try and demonstrate the system settings?
thanks

**Comment by bigdman1216** [comment]
The full product works.  I'll go load all my other equipment on.  This plugin looks great.  I'm excited to check it out.

**Comment by rlogiacco** [comment]
The Arduino perspective you had selected was the previous _V2 related_ perspective. That perspective is a leftover due to perspective id change occurred in Toddler (aka V3). You should be able to open another Arduino perspective (same name, same icon, but diferent id) and delete the old Arduino perspective. The indication is a dangling perspective comes from the double angular quotes surrounding the name and the missing icon.

You can also remove the orphaned perspective to clean up your workspace, if you wish so.

**Comment by jantje** [comment]
@bigdman1216 
Is this fixed now?

**Comment by bigdman1216** [comment]
Yes, I downloaded the product and it works.  I'll set up patron support
tomorrow.  :) great work.

**Comment by jantje** [comment]
Thanks
I'll close this issue then.
