### ISSUE TITLE
serial monitor: fixed-width font

### ISSUE THREAD

**Issue by jonbarril** [jantje/arduino-eclipse-plugin#501]
Fixed-width font is useful in serial monitor for formatting output.  Please make this an option.

**Comment by jantje** [comment]
it is an option. Look in windows->preferences->general->appearances->colors and fonts

**Comment by jonbarril** [comment]
Learned something new ... thanks!

BTW: Have been using the plugin for a couple weeks and it is great!  
Thanks for all your hard work.

--jon

**Comment by jantje** [comment]
@jonbarril 
>BTW: Have been using the plugin for a couple weeks and it is great! Thanks for all your hard work.

Thanks I needed that :-)
