### ISSUE TITLE
Missing message: doYouWantToBuildBeforeUpload

### ISSUE THREAD

**Issue by EdwinCroissant** [jantje/arduino-eclipse-plugin#519]
One picture can say more then a thousand words :)

![missing message](https://cloud.githubusercontent.com/assets/16426116/17475709/98c9ce3c-5d5c-11e6-9717-2909b9ba8552.PNG)

Windows 10 and the nightly.

**Comment by jantje** [comment]
Thanks
Should be fixed tomorrow :-)

**Comment by EdwinCroissant** [comment]
It's fixed, thank you!
Did the nag screen became more frequent in the process?

**Comment by jantje** [comment]
Thanks for confirming it works.
I'm working on a way for my Patron to not have to see this anymore. Once that works I'll probably increase the nag frequency.
But I have seen it quite a lot as well lately, So I may have left some debugging parameters in the code when debugging. I should take a look.

**Comment by jrobert-gh** [comment]
[Semi-related]: Where can I find/change this preference?

**Comment by jantje** [comment]
I just updated the patreon awards to include a nag-less experience :-)

**Comment by jrobert-gh** [comment]
Excellent! 

(But if that was a reply to my few-minutes-ago question, I don't understand. I'm looking for how to turn-on/off auto build-before-upload. I turned it off in a pop-up dialog some time ago. Now I can't find it to turn it on again.

**Comment by jantje** [comment]
The options are in windows->preferences->arduino

**Comment by jantje** [comment]
closing as this was a nightly regression.
