### ISSUE TITLE
Method variants not recognized by the GUI

### ISSUE THREAD

**Issue by sven-borkert** [jantje/arduino-eclipse-plugin#520]
Hi,

I'm using Version 3.1 of the Arduino Eclipse Plugin, 64 Bit on Windows. I installed the platform "esp8266", version "2.3.0". Creating a new sketch from the example code "ESP8266WiFi" -> "WiFiScan" shows this lines with an error:
`
Serial.print(WiFi.SSID(i));
Serial.print(WiFi.RSSI(i));
`
The GUI does not know the "print" method with parameter type "String" and does not know the "SSID" and "RSSI" methods with int parameter.

Building the projects works without any error. The original Arduino IDE and the Visual Studio Arduino Plugin don't show any problem here. It seems that the Eclipse Plugin does not fully scan/understand the includes.

Regards,

Sven

**Comment by jantje** [comment]
As an independent open source project we value your submission, but we ask for support, either by helping us out coding (yeah, we do understand it does require time) or a Patreon contribution (starting from as low as 1$ a month): this allows us to support people who support us back!
As a supporter you can drag our attention and prioritize your submission...
please become a supporter!
https://www.patreon.com/jantje

Apart from that See **FAQ** http://eclipse.baeyens.it/faq.shtml#/troubleshooting Section "Eclipse tells me there are bugs in my code but it compiles ok."
