### ISSUE TITLE
Fixed-width font for "Serial Monitor View" windows

### ISSUE THREAD

**Issue by jrobert-gh** [jantje/arduino-eclipse-plugin#525]
... would allow one to format the MCU's terminal output. Not doable with variable width fonts.

**Comment by jantje** [comment]
Are you talking about the serial monitor font?

**Comment by jrobert-gh** [comment]
Yes - the tab  called "Serial Monitor View". (Issue title updated).

**Comment by jantje** [comment]
You can change the font in windows->preferences->general->appearances->Colors and Fonts->Arduino->Serial Monitor->font

**Comment by jrobert-gh** [comment]
Perfect - thanks!
#525 is solved.

**Comment by jantje** [comment]
:-)
