### ISSUE TITLE
Feature Request:  Faster Way to Switch Board & Port

### ISSUE THREAD

**Issue by keith204** [jantje/arduino-eclipse-plugin#561]
I have been using Sloeber for a couple weeks and love it.  That is, all except for the process of switching boards & ports.  That's something I do frequently, and I found the Arduino IDE to be quicker. 

From what I understand, changing a board/port with Sloeber/eclipse can only be done by going into project preferences and selecting the boards/ports there.  

It's a first world problem, I know.  

Perhaps there's a different way to accomplish a natural workflow, like multiple projects referencing the same files.  I have not found a solution yet.  If you have any ideas, let me know, or feel free to tell me to get over it and just get used to the extra button clicks.  

A few of the extra button clicks are due to the length of file path in the board selector.  I'll work on finding a way to move this to a new directory or reference a directory junction.

**Comment by jantje** [comment]
>From what I understand, changing a board/port with Sloeber/eclipse can only be done by going into project preferences and selecting the boards/ports there. 

Yes .... but... You can have multiple configurations for a project. So if you have a limited set of boards you can setup a configuration for each board and switch configuration. Switching configuration can be done by rightclicking the project->build configurations->set active.
You can also use the cdt toolbar that has a combo to select the configuration to build.

As an independent open source project we value your submission, but we ask for support, either by helping us out coding (yeah, we do understand it does require time) or a Patreon contribution (starting from as low as 1$ a month): this allows us to support people who support us back!
As a supporter you can drag our attention and prioritize your submission...
please become a supporter!
https://www.patreon.com/jantje
