### ISSUE TITLE
V4 update site does not work

### ISSUE THREAD

**Issue by jantje** [jantje/arduino-eclipse-plugin#563]
When downloading a V4 from the nightly and running a update (after a new build) the update does not not find updates.
You can however add the plugin but then I have 2 arduino perspectives.
It looks like the refactoring to io.sloeber was not fully successful yet.

**Comment by jantje** [comment]
Checking again I see that the version I could install is V3.1. Which makes sense.
Removing the flag "Hide items that are already installed" reveals no other items.
So it looks as if the nightly update site does not contain a V4 version.
@wimjongman @rlogiacco 
Maybe I should make a V4 nightly?

**Comment by jantje** [comment]
I found that jenkins still uses it.baeyens for copying the nightly. So that is a easy fix.
Before I fix this I would like to have a decision on the target.

- nightly
- V4/nightly
- V4_nightly
- ....

**Comment by jantje** [comment]
I wanted to fix #564 but it turns out it is closely related to my question here.
So I looked a bit closer and this makes sense to me.
![updatesites](https://cloud.githubusercontent.com/assets/1175841/19830244/d03ecf98-9df3-11e6-898a-1c14f108ef8b.PNG)

**Comment by wimjongman** [comment]
+1

**Comment by jantje** [comment]
closing as this is nightly regression
