### ISSUE TITLE
#define not properly parsed?

### ISSUE THREAD

**Issue by freeck** [jantje/arduino-eclipse-plugin#580]
Building this code:
 `
#define ICACHE ICACHE_FLASH_ATTR

#define RAMFUNC __attribute__((section(".entry.text")))

void ICACHE_FLASH_ATTR toggleIoPins() {
}
void ICACHE toggleIoPins2() {
}`
Leads to the following error:
../.ino.cpp:11:13: error: expected initializer before 'toggleIoPins2'
 void ICACHE toggleIoPins2() ;

ICACHE_FLASH_ATTR is defined in c_types.h
In case I include #define RAMFUNC __attribute__((section(".entry.text"))) in file c_types.h , this is not properly processed, I observe that the pointer to the error message (line number) is not synchronous with the original source line.

**Comment by jantje** [comment]
This is actually very similar to this know limitation https://github.com/jantje/arduino-eclipse-plugin/issues/478
Read this article on how to handle this situation:
https://www.patreon.com/posts/defines-before-6795548

As an independent open source project we value your submission, but we ask for support, either by helping us out coding (yeah, we do understand it does require time) or a Patreon contribution (starting from as low as 1$ a month): this allows us to support people who support us back!
As a supporter you can drag our attention and prioritize your submission...
please become a supporter!
https://www.patreon.com/jantje
