### ISSUE TITLE
V4: compile options Arduino not saved

### ISSUE THREAD

**Issue by freeck** [jantje/arduino-eclipse-plugin#592]
In case I try to set compile options via menu: Project->Properties->Arduino->Compile Options to i.e. "-ggdb -Og" .
The compiler parameters are not saved. The parameters are all cleared when you read them...

**Comment by jantje** [comment]
Thanks for the input.
Will have a look :-)

**Comment by jantje** [comment]
Confirmed.
Will try to look at this tonight.

**Comment by jantje** [comment]
Apparently this is not yet implemented. Thanks for finding this :-)

**Comment by jantje** [comment]
Should be fixed with the V4 nightly after 6:00 GMT

**Comment by jantje** [comment]
Works here now :-)

**Comment by freeck** [comment]
Confirm saving build-parameters. Thanks!! Case closed.
