### ISSUE TITLE
Include file is not processed as in Arduino IDE

### ISSUE THREAD

**Issue by fred-maria** [jantje/arduino-eclipse-plugin#612]
Hello,
when including an header file from a sketch <sketch_name>.ino, if the header file depends on any C item (define, variable, etc.) then compilation yields an error.
(ok, this is may be not a good programming practice, but I need this feature).

The issue comes by the fact that Sloeber add the include file directly in the .ino.cpp file before to include the <sketch_name.ino> file.

I have attached a very simple sketch that perfectly works in the Arduino IDE, but doesn't in Sloeber.

Removing the #include from the .ino.cpp file should fix the issue.

Well, thanks anyway for your work on Sloeber plugin.

[issue_include.zip](https://github.com/jantje/arduino-eclipse-plugin/files/675965/issue_include.zip)

**Comment by jantje** [comment]
this is a known limitation.
https://github.com/jantje/arduino-eclipse-plugin/issues/478
