### ISSUE TITLE
Document how to use OTA

### ISSUE THREAD

**Issue by judge2005** [jantje/arduino-eclipse-plugin#626]
Hi,

Firstly, many thanks for this project. I wish all Arduino developers used it.

I am using it to program an ESP8266 and would like to use OTA. I have managed to find some other issues that talk about this, but it would be great if this were documented on your web site, as I am still not sure exactly how this works with your plugin.

Thanks - Paul

**Comment by jantje** [comment]
It is documented here
https://www.youtube.com/watch?v=MGAyIOC24lU


As an independent open source project we value your submission, but we ask for support, either by helping us out coding (yeah, we do understand it does require time) or a Patreon contribution (starting from as low as 1$ a month): this allows us to support people who support us back!
As a supporter you can drag our attention and prioritize your submission...
please become a supporter!
https://www.patreon.com/jantje
